version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout

      - run: gradle test

workflows:
  version: 2
  build-padrao:
    jobs:
      - build
