spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    ddl-auto: none
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: '' #${EMAIL_USERNAME}
    password: '' #${EMAIL_PASSWORD}
    port: 587
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp