server:
  port: ${PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOSPEBEM_DB_HOST:localhost}:${HOSPEBEM_DB_PORT:5432}/${HOSPEBEM_DB_NAME:hospebem}
    username: ${HOSPEBEM_DB_USER:postgres}
    password: ${HOSPEBEM_DB_PASSWORD:hospebem}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    ddl-auto: none
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

